name: eCore
version: 0.5
main: com.mcdr.ecore.eCore
softdepend: [Corruption]
commands:
    ecore:
        usage: /ecore reload
        description:
    ks:
        usage: /ks <...args>
        description:
    as:
        usage: /as <...args>
        description: